[mypy]
python_version = 3.11
strict_optional = True
warn_unused_ignores = True
warn_redundant_casts = True
warn_return_any = True
ignore_missing_imports = True
exclude = (venv|build|data|\.venv)

[mypy-fire_safety_rag.*]
disallow_untyped_defs = False

[mypy-fire_safety_backend.*]
disallow_untyped_defs = False
